### ISSUE TITLE
Compatible with WS2801?

### ISSUE THREAD

**Issue by kami004** [SolidStateGroup/rio#16]
Hi there. Love your project and currently try to set it up at home.
Before I continue to the software issues (where I am currently stuck): Can I also use this software with my WS2801 Pixels? Currently connected them in this setup (https://tutorials-raspberrypi.de/raspberry-pi-openhab-2-ws2801-ws2812-rgb-led-streifen-steuern/).

I followed all your instructions for my Pi but when I try to install the server, I just get issues.

`pi@raspberrypi:~ $ cd rio && npm run install-server                
(node:3343) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> rio@0.0.1 install-server /home/pi/rio
> cd ./rio-server && npm i

(node:3354) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json rio-server@1.0.0 No repository field.
npm WARN package.json rio-server@1.0.0 No license field.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! cwd /home/pi/rio/rio-server
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/rio/rio-server/npm-debug.log
npm ERR! not ok code 0

npm ERR! rio@0.0.1 install-server: `cd ./rio-server && npm i`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rio@0.0.1 install-server script.
npm ERR! This is most likely a problem with the rio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./rio-server && npm i
npm ERR! You can get their info via:
npm ERR!     npm owner ls rio
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "install-server"
npm ERR! cwd /home/pi/rio
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/rio/npm-debug.log
npm ERR! not ok code 0
`

Content of npm-debug.log
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'install-server' ]
2 info using npm@1.4.21
3 info using node@v8.11.1
4 verbose run-script [ 'preinstall-server', 'install-server', 'postinstall-server' ]
5 info preinstall-server rio@0.0.1
6 info install-server rio@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info rio@0.0.1 Failed to exec install-server script
9 error rio@0.0.1 install-server: `cd ./rio-server && npm i`
9 error Exit status 1
10 error Failed at the rio@0.0.1 install-server script.
10 error This is most likely a problem with the rio package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     cd ./rio-server && npm i
10 error You can get their info via:
10 error     npm owner ls rio
10 error There is likely additional logging output above.
11 error System Linux 4.14.79+
12 error command "/usr/bin/node" "/usr/bin/npm" "run" "install-server"
13 error cwd /home/pi/rio
14 error node -v v8.11.1
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]`

Thanks guys! Really appreciate your help.

**Comment by lukefanning** [comment]
Your npm version is incredibly old. Please try upgrading that to at least v5. Run `npm install -g npm@5`

**Comment by kami004** [comment]
Thanks @ssg-luke , that already helped a lot. Installation went smooth afterwards. Weird btw, I had a freshly installed RPi do know why it somehow grabbed such an old version. anyway.

When I now "npm run server" seems like I run out of memory.

`pi@raspberrypi:~/rio $ npm run server

> rio@0.0.1 server /home/pi/rio
> cd ./rio-server && npm start


> rio-server@1.0.0 start /home/pi/rio/rio-server
> node index.js


<--- Last few GCs --->

[3909:0x26f2588]    15498 ms: Mark-sweep 13.6 (30.6) -> 11.3 (30.5) MB, 101.1 / 0.3 ms  (+ 724.8 ms in 652 steps since start of marking, biggest step 20.9 ms, walltime since start of marking 1234 ms) finalize incremental marking via task GC in old space r[3909:0x26f2588]   177258 ms: Mark-sweep 15.2 (30.5) -> 15.1 (22.5) MB, 10515.7 / 231.1 ms  (+ 33896.8 ms in 579 steps since start of marking, biggest step 17522.8 ms, walltime since start of marking 51436 ms) finalize incremental marking via task GC in o

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x5b41631d <JSObject>
    0: builtin exit frame: parse(this=0x5b411405 <Object map = 0x4138593d>,0x58229711 <Very long string[7083670]>)

    2: onread [internal/child_process.js:470] [bytecode=0x36e75a15 offset=148](this=0x309b3055 <Pipe map = 0x44f8480d>,nread=21591,pool=0x58224221 <Uint8Array map = 0x44f841b1>,recvHandle=0x309841a1 <undefined>)

==== Details ================================================

[0]: built...

FATAL ERROR: Zone Allocation failed - process out of memory
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! rio-server@1.0.0 start: `node index.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the rio-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-02-13T18_36_03_661Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! rio@0.0.1 server: `cd ./rio-server && npm start`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the rio@0.0.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-02-13T18_36_06_409Z-debug.log`

The debug.long reads
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'server' ]
2 info using npm@5.10.0
3 info using node@v8.9.0
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle rio@0.0.1~preserver: rio@0.0.1
6 info lifecycle rio@0.0.1~server: rio@0.0.1
7 verbose lifecycle rio@0.0.1~server: unsafe-perm in lifecycle true
8 verbose lifecycle rio@0.0.1~server: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/rio/node_modules/.b$
9 verbose lifecycle rio@0.0.1~server: CWD: /home/pi/rio
10 silly lifecycle rio@0.0.1~server: Args: [ '-c', 'cd ./rio-server && npm start' ]
11 silly lifecycle rio@0.0.1~server: Returned: code: 134  signal: null
12 info lifecycle rio@0.0.1~server: Failed to exec server script
13 verbose stack Error: rio@0.0.1 server: `cd ./rio-server && npm start`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rio@0.0.1
15 verbose cwd /home/pi/rio
16 verbose Linux 4.14.79+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
18 verbose node v8.9.0
19 verbose npm  v5.10.0
20 error code ELIFECYCLE
21 error errno 134
22 error rio@0.0.1 server: `cd ./rio-server && npm start`
22 error Exit status 134
23 error Failed at the rio@0.0.1 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]



Still wondering: Can I really set this up with ws2801? mine are connected with two gpio pins like mentioned in the url above.

Thanks
