### ISSUE TITLE
Cannot run rio-server on rpi2 model b, ubuntu server 20.04

### ISSUE THREAD

**Issue by nys99** [SolidStateGroup/rio#58]
I am trying to run the rio-server on a raspberry pi 2 model b with Ubuntu Server 20.04 as the operating system.

I followed the install instructions and I am able to run rio server outputting to the console. I am also able to run singlestrandtest.py and get my LEDs to light up. But when I run the rio server with the sendToPi enabled I get the error:

```
ubuntu@ubuntu:~/rio$ sudo npm run server

> rio@0.0.1 server /home/ubuntu/rio
> cd ./rio-server && npm start


> rio-server@1.0.0 start /home/ubuntu/rio/rio-server
> node index.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rio-server@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rio-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-08T04_42_35_492Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rio@0.0.1 server: `cd ./rio-server && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rio@0.0.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-08T04_42_35_601Z-debug.log
```

**Comment by lukefanning** [comment]
Hi, it appears as though it is trying to run Python v2 which probably is not installed on your RPi as it is obsolete.

You will need to update the python-shell package. Open package.json and change the version for python-shell to 3.0.0. Run `npm i` and then try starting it again

**Comment by nys99** [comment]
Ah, I ended up installing the Rpi OS instead of Ubuntu. This solved the python issue, but now I have another issue for which I will open another issue for. Thank you for the quick response!
